from dataclasses import dataclass, field
from typing import List

@dataclass
class ParticleFormat:
    """Data class representing particle properties for physics simulations.

    Attributes:
        code (int): PDG code of the particle.
        name (str): Name of the particle.
        antiname (str): Name of the antiparticle.
        spinType (int): Twice the particle's spin plus one (2s + 1).
        chargeType (int): Three times the electric charge.
        colType (int): Colour representation of the particle.
            0: uncoloured,
            ±1: (anti-) triplet,
            2: octet,
            ±3: (anti-) sextet.
        m0 (float): Mass of the particle in GeV.
        mWidth (float): Breit-Wigner width in GeV.
        mMin (float): Lower limit for mass generated by Breit-Wigner.
        mMax (float): Upper limit for mass generated by Breit-Wigner.
        tau0 (float): Proper lifetime in millimeters.
        tauCalc (bool): Flag indicating whether the lifetime should be calculated
            from the particle's width (`mWidth`).
        isResonance (bool): Flag indicating whether the particle is considered a resonance.
        mayDecay (bool): Flag indicating whether the particle is allowed to decay.
        doExternalDecay (bool): Flag indicating whether decay should use an external package.
        isVisible (bool): Flag indicating whether the particle is considered visible by detectors.
        doForceWidth (bool): Flag applicable only for resonances, forcing usage of the specified width.
    """
    code:            int   #pdg code of the particle
    name:            str   #name of the particle
    antiname:        str   #name of the antiparticle
    spinType:        int   #integer equal to 2s + 1
    chargeType:      int   #three times the electric charge
    colType:         int   #colour representation, 0 uncoloured, (-1)1 (anti-) triplet, 2 : octet, (-3)3 (anti-) sextet
    m0:              float #Mass of the particle in GeV
    mWidth:          float #Breit-Wigner width in GeV
    mMin:            float #lower limit for mass generated by the Brit-Wigner
    mMax:            float #upper limit for mass generated by the Brit-Wigner
    tau0:            float #proper lifetime in mm
    tauCalc:         bool  #flag telling whether the lifetime should be calculated from the particle width mWidth
    isResonance:     bool  #Telling whether a particle should be consider as a resonance.
    mayDecay:        bool  #set whether the particle is allowed to decay
    doExternalDecay: bool  #flag telling if decay should use external package
    isVisible:       bool  #set whether the particle is consider to be visible by the detector
    doForceWidth:    bool  #a flag applicatble only for resonnance
    
    def __repr__(self):
        return f"{self.code}:new {self.name} {self.antiname} {self.spinType} {self.chargeType} {self.colType} {self.m0} {self.mWidth} {self.mMin} {self.mMax} {self.tau0} {int(self.tauCalc)} {int(self.isResonance)} {int(self.mayDecay)} {int(self.doExternalDecay)} {int(self.isVisible)} {int(self.doForceWidth)}"
    
    
@dataclass
class DecayFormat:
    """Data class representing decay channel properties for physics simulations.

    Attributes:
        code (int): PDG code of the particle undergoing decay.
        onMode (int): Indicates if the decay is enabled.
            0: decay off,
            1: decay on,
            2: decay on for particle only,
            3: decay on for antiparticle only.
        bRatio (float): Branching ratio for this decay channel.
        meMode (int): Decay handling mode, determining matrix element reweighting.
            Default is 0 (flat phase space).
        multiplicity (int): Number of daughter particles (maximum 8).
        products (List[int]): List of PDG IDs for daughter particles.

    Raises:
        ValueError: If the number of provided product IDs does not match `multiplicity`.
    """
    code:          int                                      #pdgcode of the particle
    onMode :       int                                      #Set whether the decay is open where 0 is off, 1 is on, 2 on for the particle but not the antiparticle, 3 for the antiparticle and not the particle
    bRatio :       float                                    #Branching ratio for the channel
    meMode :       int                                      #How the decay is handled, in particlar whether internal matrix element reweighteing is available to account for the mass or angular correlation. Default is 0 corresponding to flat phase space.
    multiplicity : int                                      #Number of daughters, maximum 8
    products:      List[int] = field(default_factory=list)  #List of pdg id for particles

    def __post_init__(self):
        if len(self.products) != self.multiplicity:
            raise ValueError(f"Expected {self.multiplicity} products, got {len(self.products)}.")

    def __repr__(self):
        products_str = ' '.join(str(p) for p in self.products)
        return f"{self.code}:addChannel = {self.onMode} {self.bRatio} {self.meMode} {products_str}"
    